# fly.toml file generated for morning-sun-6939 on 2023-04-10T12:27:44+03:00

app = "morning-sun-6939"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "arn"

[env]
  PORT = "3001"

[[services]]
  protocol = "tcp"
  internal_port = 3001
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
